#!/bin/sh

for BAT in /sys/class/power_supply/BAT*
do
    printf "\n"
    printf "%s:\n" "$BAT"
    printf "  Manufacturer: %s\n" "$(cat "$BAT"/manufacturer)"
    printf "  Model: %s\n" "$(cat "$BAT"/model_name)"
    printf "  Capacity: %s\n" "$(cat "$BAT"/capacity)"
    printf "  Status: %s\n" "$(cat "$BAT"/status)"
    printf "  Energy full: %s\n" "$(cat "$BAT"/energy_full)"
    printf "  Energy full designed: %s\n" "$(cat "$BAT"/energy_full_design)"
    printf "  Cycle count: %s\n" "$(cat "$BAT"/cycle_count)"
    AGED_PER="$(printf "scale=4; 100 - 100 * %s / %s\n" "$(cat "$BAT"/energy_full)" "$(cat "$BAT"/energy_full_design)" | bc)"
    printf "  Aged: %s%%\n" "$AGED_PER"
done
