#!/bin/sh

clock () {
        DATETIME=$(date "+%T")
        echo -n "$DATETIME"
}

volume () {
    LINE=$(amixer sget Master 2> /dev/null | grep "%" | head -n 1 | sed -e 's/\[\|\]//g')
    VOL=$(echo $LINE |  awk '{print $5}')
    STATUS=$(echo $LINE |  awk '{print $6}')

    if [ "$STATUS" = "on" ]; then
        echo -n "VOL $VOL"
    else
        echo -n "MUTE $VOL"
    fi
}

battery () {
    BAT=/sys/class/power_supply/BAT0
    THRESHOLD_WARNING=20
    THRESHOLD_CRITICAL=10

    CAPACITY=$(cat $BAT/capacity)
    STATUS=$(cat $BAT/status)

    if [ "$STATUS" = "Discharging" ]; then
        echo -n "BAT $CAPACITY%"
    else
        echo -n "PLUG $CAPACITY%"
    fi
}

info () {
    while :
    do
        xsetroot -name "$(battery)  $(volume)  $(clock) "
        sleep 0.5
    done
}

~/bin/autostart

info &

. ~/.cache/wal/colors.sh
exec dwm -fn Terminus:pixelsize=12 -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15" -df Terminus:pixelsize=12 -dnb "$color0" -dnf "$color15" -dsb "$color1" -dsf "$color15"
