#!/bin/sh

~/bin/autostart &
~/bin/dwminfo &

. ~/.cache/wal/colors.sh

exec dwm -fn Terminus:pixelsize=12 -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15" -df Terminus:pixelsize=12 -dnb "$color0" -dnf "$color15" -dsb "$color1" -dsf "$color15"
