#!/bin/sh

clock () {
        DATETIME=$(date "+%Y-%m-%d %T")
        echo -n "$DATETIME"
}

volume () {
    LINE=$(amixer sget Master 2> /dev/null | grep "%" | head -n 1 | sed -e 's/\[\|\]//g')
    VOL=$(echo $LINE |  awk '{print $5}')
    STATUS=$(echo $LINE |  awk '{print $6}')

    if [ "$STATUS" = "on" ]; then
        echo -n "V$VOL"
    else
        echo -n "V--%"
    fi
}

battery () {
    BAT=/sys/class/power_supply/BAT0
    THRESHOLD_WARNING=20
    THRESHOLD_CRITICAL=10

    if [ ! -e $BAT ]; then
        exit
    fi

    CAPACITY=$(cat $BAT/capacity)
    STATUS=$(cat $BAT/status)

    if [ "$STATUS" = "Discharging" ]; then
        echo -n "B$CAPACITY%"
    else
        echo -n "C$CAPACITY%"
    fi
}

im () {
    case $(fcitx5-remote) in
        0 )
            echo -n "--"
            ;;
        1 )
            echo -n "EN"
            ;;
        2 )
            echo -n "JP"
            ;;
    esac
}

mem () {
    MEM=$(free -h | grep "^Mem:")
    TOTAL=$(echo $MEM | awk '{print $2}' | tr -d i)
    USED=$(echo $MEM | awk '{print $3}' | tr -d i)
    echo -n "$USED/$TOTAL"
}

info () {
    MYPID=$$
    OLDPID=$(ps ax | grep sh | grep dwminfo | grep -v $MYPID | grep -v grep | awk '{print $1}')

    if [ "$OLDPID" != "" ]; then
        kill -9  $OLDPID 2> /dev/null
    fi

    while :
    do
        xsetroot -name "$(mem)  $(im)  $(battery)  $(volume)  $(clock) "
        sleep 0.2
    done
}

info
