#!/bin/sh

FILE="$1"

if ! type openscad > /dev/null 2>&1; then
    printf "OpenSCAD is unavailable\n"
    exit 1
fi

if [ -z "$FILE" ]; then
    printf "usage: oscad FILE\n"
    exit 1
fi

if [ ! -f "$FILE" ]; then
    if ! touch "$FILE"; then
        printf "Cannot open %s\n" "$FILE"
        exit 1
    fi
fi

openscad "$FILE" 2> /dev/null &
PID="$!"

vim "$FILE"
kill "$PID" 2> /dev/null
