#!/bin/sh

export DST=~/Pictures/screenshots

case $1 in
	's' ) OPT="-s" ;;
esac

if [ ! -d ${DST} ]; then
	mkdir -p ${DST}
fi

DATE=$(date "+%Y%m%d_%H%M%S_")
NSEC=$(date "+%N")
TMSEC=$(printf %02d $(expr $NSEC / 1000 / 1000 / 10 ))
OUT=$DATE$TMSEC.png

maim $OPT --hidecursor $DST/$OUT
