#!/bin/sh

DIR=./

if [ -n "$1" ]; then
    DIR="$1"
fi

if [ ! -d "$DIR" ]; then
    printf "%s is not a directory\n" "$DIR" 1>&2
    exit 1
fi

for dir in $(mount | awk '{print $3}' | grep "^$(readlink -f "$DIR")")
do
    umount -R "$dir"
done
